package com.yqritc.scalablevideoview;

public enum b {
  CENTER, CENTER_BOTTOM, CENTER_BOTTOM_CROP, CENTER_CROP, CENTER_INSIDE, CENTER_TOP, CENTER_TOP_CROP, END_INSIDE, FIT_CENTER, FIT_END, FIT_START, FIT_XY, LEFT_BOTTOM, LEFT_BOTTOM_CROP, LEFT_CENTER, LEFT_CENTER_CROP, LEFT_TOP, LEFT_TOP_CROP, NONE, RIGHT_BOTTOM, RIGHT_BOTTOM_CROP, RIGHT_CENTER, RIGHT_CENTER_CROP, RIGHT_TOP, RIGHT_TOP_CROP, START_INSIDE;
  
  static {
    FIT_XY = new b("FIT_XY", 1);
    FIT_START = new b("FIT_START", 2);
    FIT_CENTER = new b("FIT_CENTER", 3);
    FIT_END = new b("FIT_END", 4);
    LEFT_TOP = new b("LEFT_TOP", 5);
    LEFT_CENTER = new b("LEFT_CENTER", 6);
    LEFT_BOTTOM = new b("LEFT_BOTTOM", 7);
    CENTER_TOP = new b("CENTER_TOP", 8);
    CENTER = new b("CENTER", 9);
    CENTER_BOTTOM = new b("CENTER_BOTTOM", 10);
    RIGHT_TOP = new b("RIGHT_TOP", 11);
    RIGHT_CENTER = new b("RIGHT_CENTER", 12);
    RIGHT_BOTTOM = new b("RIGHT_BOTTOM", 13);
    LEFT_TOP_CROP = new b("LEFT_TOP_CROP", 14);
    LEFT_CENTER_CROP = new b("LEFT_CENTER_CROP", 15);
    LEFT_BOTTOM_CROP = new b("LEFT_BOTTOM_CROP", 16);
    CENTER_TOP_CROP = new b("CENTER_TOP_CROP", 17);
    CENTER_CROP = new b("CENTER_CROP", 18);
    CENTER_BOTTOM_CROP = new b("CENTER_BOTTOM_CROP", 19);
    RIGHT_TOP_CROP = new b("RIGHT_TOP_CROP", 20);
    RIGHT_CENTER_CROP = new b("RIGHT_CENTER_CROP", 21);
    RIGHT_BOTTOM_CROP = new b("RIGHT_BOTTOM_CROP", 22);
    START_INSIDE = new b("START_INSIDE", 23);
    CENTER_INSIDE = new b("CENTER_INSIDE", 24);
    END_INSIDE = new b("END_INSIDE", 25);
    a = new b[] { 
        NONE, FIT_XY, FIT_START, FIT_CENTER, FIT_END, LEFT_TOP, LEFT_CENTER, LEFT_BOTTOM, CENTER_TOP, CENTER, 
        CENTER_BOTTOM, RIGHT_TOP, RIGHT_CENTER, RIGHT_BOTTOM, LEFT_TOP_CROP, LEFT_CENTER_CROP, LEFT_BOTTOM_CROP, CENTER_TOP_CROP, CENTER_CROP, CENTER_BOTTOM_CROP, 
        RIGHT_TOP_CROP, RIGHT_CENTER_CROP, RIGHT_BOTTOM_CROP, START_INSIDE, CENTER_INSIDE, END_INSIDE };
  }
}


/* Location:              C:\Users\august\Desktop\tik\df_rn_kit\classes.jar.jar!\com\yqritc\scalablevideoview\b.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */