package com.facebook.react.bridge;

public enum ReactMarkerConstants {
  ATTACH_MEASURED_ROOT_VIEWS_END, ATTACH_MEASURED_ROOT_VIEWS_START, BUILD_NATIVE_MODULE_REGISTRY_END, BUILD_NATIVE_MODULE_REGISTRY_START, BUILD_REACT_INSTANCE_MANAGER_END, BUILD_REACT_INSTANCE_MANAGER_START, CONTENT_APPEARED, CONVERT_CONSTANTS_END, CONVERT_CONSTANTS_START, CREATE_CATALYST_INSTANCE_END, CREATE_CATALYST_INSTANCE_START, CREATE_I18N_ASSETS_MODULE_END, CREATE_I18N_ASSETS_MODULE_START, CREATE_I18N_MODULE_CONSTANTS_END, CREATE_I18N_MODULE_CONSTANTS_START, CREATE_MC_MODULE_END, CREATE_MC_MODULE_GET_METADATA_END, CREATE_MC_MODULE_GET_METADATA_START, CREATE_MC_MODULE_START, CREATE_MODULE_END, CREATE_MODULE_START, CREATE_REACT_CONTEXT_END, CREATE_REACT_CONTEXT_START, CREATE_UI_MANAGER_MODULE_CONSTANTS_END, CREATE_UI_MANAGER_MODULE_CONSTANTS_START, CREATE_UI_MANAGER_MODULE_END, CREATE_UI_MANAGER_MODULE_START, CREATE_VIEW_MANAGERS_END, CREATE_VIEW_MANAGERS_START, DESTROY_CATALYST_INSTANCE_END, DESTROY_CATALYST_INSTANCE_START, DOWNLOAD_END, DOWNLOAD_START, GET_CONSTANTS_END, GET_CONSTANTS_START, GET_REACT_INSTANCE_HOLDER_SPEC_END, GET_REACT_INSTANCE_HOLDER_SPEC_START, GET_REACT_INSTANCE_MANAGER_END, GET_REACT_INSTANCE_MANAGER_START, I18N_MODULE_CONSTANTS_CONVERT_END, I18N_MODULE_CONSTANTS_CONVERT_START, INITIALIZE_MODULE_END, INITIALIZE_MODULE_START, NATIVE_MODULE_INITIALIZE_END, NATIVE_MODULE_INITIALIZE_START, NATIVE_MODULE_SETUP_END, NATIVE_MODULE_SETUP_START, ON_HOST_PAUSE_END, ON_HOST_PAUSE_START, ON_HOST_RESUME_END, ON_HOST_RESUME_START, PRE_REACT_CONTEXT_END, PRE_RUN_JS_BUNDLE_START, PRE_SETUP_REACT_CONTEXT_END, PRE_SETUP_REACT_CONTEXT_START, PROCESS_CORE_REACT_PACKAGE_END, PROCESS_CORE_REACT_PACKAGE_START, PROCESS_INFRA_PACKAGE_END, PROCESS_INFRA_PACKAGE_START, PROCESS_PACKAGES_END, PROCESS_PACKAGES_START, PROCESS_PRODUCT_PACKAGE_END, PROCESS_PRODUCT_PACKAGE_START, REACT_CONTEXT_THREAD_END, REACT_CONTEXT_THREAD_START, RELOAD, RUN_JS_BUNDLE_END, RUN_JS_BUNDLE_START, SETUP_REACT_CONTEXT_END, SETUP_REACT_CONTEXT_START, UNPACKING_JS_BUNDLE_LOADER_BLOCKED, UNPACKING_JS_BUNDLE_LOADER_CHECK_END, UNPACKING_JS_BUNDLE_LOADER_CHECK_START, UNPACKING_JS_BUNDLE_LOADER_EXTRACTED, loadApplicationScript_endStringConvert, loadApplicationScript_startStringConvert;
  
  static {
    CREATE_REACT_CONTEXT_END = new ReactMarkerConstants("CREATE_REACT_CONTEXT_END", 1);
    PROCESS_PACKAGES_START = new ReactMarkerConstants("PROCESS_PACKAGES_START", 2);
    PROCESS_PACKAGES_END = new ReactMarkerConstants("PROCESS_PACKAGES_END", 3);
    BUILD_NATIVE_MODULE_REGISTRY_START = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_START", 4);
    BUILD_NATIVE_MODULE_REGISTRY_END = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_END", 5);
    CREATE_CATALYST_INSTANCE_START = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_START", 6);
    CREATE_CATALYST_INSTANCE_END = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_END", 7);
    DESTROY_CATALYST_INSTANCE_START = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_START", 8);
    DESTROY_CATALYST_INSTANCE_END = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_END", 9);
    RUN_JS_BUNDLE_START = new ReactMarkerConstants("RUN_JS_BUNDLE_START", 10);
    RUN_JS_BUNDLE_END = new ReactMarkerConstants("RUN_JS_BUNDLE_END", 11);
    NATIVE_MODULE_INITIALIZE_START = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_START", 12);
    NATIVE_MODULE_INITIALIZE_END = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_END", 13);
    SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("SETUP_REACT_CONTEXT_START", 14);
    SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("SETUP_REACT_CONTEXT_END", 15);
    CREATE_UI_MANAGER_MODULE_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_START", 16);
    CREATE_UI_MANAGER_MODULE_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_END", 17);
    CREATE_VIEW_MANAGERS_START = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_START", 18);
    CREATE_VIEW_MANAGERS_END = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_END", 19);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_START", 20);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_END", 21);
    NATIVE_MODULE_SETUP_START = new ReactMarkerConstants("NATIVE_MODULE_SETUP_START", 22);
    NATIVE_MODULE_SETUP_END = new ReactMarkerConstants("NATIVE_MODULE_SETUP_END", 23);
    CREATE_MODULE_START = new ReactMarkerConstants("CREATE_MODULE_START", 24);
    CREATE_MODULE_END = new ReactMarkerConstants("CREATE_MODULE_END", 25);
    PROCESS_CORE_REACT_PACKAGE_START = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_START", 26);
    PROCESS_CORE_REACT_PACKAGE_END = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_END", 27);
    CREATE_I18N_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_START", 28);
    CREATE_I18N_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_END", 29);
    I18N_MODULE_CONSTANTS_CONVERT_START = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_START", 30);
    I18N_MODULE_CONSTANTS_CONVERT_END = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_END", 31);
    CREATE_I18N_ASSETS_MODULE_START = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_START", 32);
    CREATE_I18N_ASSETS_MODULE_END = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_END", 33);
    GET_CONSTANTS_START = new ReactMarkerConstants("GET_CONSTANTS_START", 34);
    GET_CONSTANTS_END = new ReactMarkerConstants("GET_CONSTANTS_END", 35);
    INITIALIZE_MODULE_START = new ReactMarkerConstants("INITIALIZE_MODULE_START", 36);
    INITIALIZE_MODULE_END = new ReactMarkerConstants("INITIALIZE_MODULE_END", 37);
    ON_HOST_RESUME_START = new ReactMarkerConstants("ON_HOST_RESUME_START", 38);
    ON_HOST_RESUME_END = new ReactMarkerConstants("ON_HOST_RESUME_END", 39);
    ON_HOST_PAUSE_START = new ReactMarkerConstants("ON_HOST_PAUSE_START", 40);
    ON_HOST_PAUSE_END = new ReactMarkerConstants("ON_HOST_PAUSE_END", 41);
    CONVERT_CONSTANTS_START = new ReactMarkerConstants("CONVERT_CONSTANTS_START", 42);
    CONVERT_CONSTANTS_END = new ReactMarkerConstants("CONVERT_CONSTANTS_END", 43);
    PRE_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_REACT_CONTEXT_END", 44);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_START = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_START", 45);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_END = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_END", 46);
    UNPACKING_JS_BUNDLE_LOADER_EXTRACTED = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_EXTRACTED", 47);
    UNPACKING_JS_BUNDLE_LOADER_BLOCKED = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_BLOCKED", 48);
    loadApplicationScript_startStringConvert = new ReactMarkerConstants("loadApplicationScript_startStringConvert", 49);
    loadApplicationScript_endStringConvert = new ReactMarkerConstants("loadApplicationScript_endStringConvert", 50);
    PRE_SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_START", 51);
    PRE_SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_END", 52);
    PRE_RUN_JS_BUNDLE_START = new ReactMarkerConstants("PRE_RUN_JS_BUNDLE_START", 53);
    ATTACH_MEASURED_ROOT_VIEWS_START = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_START", 54);
    ATTACH_MEASURED_ROOT_VIEWS_END = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_END", 55);
    CONTENT_APPEARED = new ReactMarkerConstants("CONTENT_APPEARED", 56);
    RELOAD = new ReactMarkerConstants("RELOAD", 57);
    DOWNLOAD_START = new ReactMarkerConstants("DOWNLOAD_START", 58);
    DOWNLOAD_END = new ReactMarkerConstants("DOWNLOAD_END", 59);
    REACT_CONTEXT_THREAD_START = new ReactMarkerConstants("REACT_CONTEXT_THREAD_START", 60);
    REACT_CONTEXT_THREAD_END = new ReactMarkerConstants("REACT_CONTEXT_THREAD_END", 61);
    GET_REACT_INSTANCE_MANAGER_START = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_START", 62);
    GET_REACT_INSTANCE_MANAGER_END = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_END", 63);
    GET_REACT_INSTANCE_HOLDER_SPEC_START = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_START", 64);
    GET_REACT_INSTANCE_HOLDER_SPEC_END = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_END", 65);
    BUILD_REACT_INSTANCE_MANAGER_START = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_START", 66);
    BUILD_REACT_INSTANCE_MANAGER_END = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_END", 67);
    PROCESS_INFRA_PACKAGE_START = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_START", 68);
    PROCESS_INFRA_PACKAGE_END = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_END", 69);
    PROCESS_PRODUCT_PACKAGE_START = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_START", 70);
    PROCESS_PRODUCT_PACKAGE_END = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_END", 71);
    CREATE_MC_MODULE_START = new ReactMarkerConstants("CREATE_MC_MODULE_START", 72);
    CREATE_MC_MODULE_END = new ReactMarkerConstants("CREATE_MC_MODULE_END", 73);
    CREATE_MC_MODULE_GET_METADATA_START = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_START", 74);
    CREATE_MC_MODULE_GET_METADATA_END = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_END", 75);
    $VALUES = new ReactMarkerConstants[] { 
        CREATE_REACT_CONTEXT_START, CREATE_REACT_CONTEXT_END, PROCESS_PACKAGES_START, PROCESS_PACKAGES_END, BUILD_NATIVE_MODULE_REGISTRY_START, BUILD_NATIVE_MODULE_REGISTRY_END, CREATE_CATALYST_INSTANCE_START, CREATE_CATALYST_INSTANCE_END, DESTROY_CATALYST_INSTANCE_START, DESTROY_CATALYST_INSTANCE_END, 
        RUN_JS_BUNDLE_START, RUN_JS_BUNDLE_END, NATIVE_MODULE_INITIALIZE_START, NATIVE_MODULE_INITIALIZE_END, SETUP_REACT_CONTEXT_START, SETUP_REACT_CONTEXT_END, CREATE_UI_MANAGER_MODULE_START, CREATE_UI_MANAGER_MODULE_END, CREATE_VIEW_MANAGERS_START, CREATE_VIEW_MANAGERS_END, 
        CREATE_UI_MANAGER_MODULE_CONSTANTS_START, CREATE_UI_MANAGER_MODULE_CONSTANTS_END, NATIVE_MODULE_SETUP_START, NATIVE_MODULE_SETUP_END, CREATE_MODULE_START, CREATE_MODULE_END, PROCESS_CORE_REACT_PACKAGE_START, PROCESS_CORE_REACT_PACKAGE_END, CREATE_I18N_MODULE_CONSTANTS_START, CREATE_I18N_MODULE_CONSTANTS_END, 
        I18N_MODULE_CONSTANTS_CONVERT_START, I18N_MODULE_CONSTANTS_CONVERT_END, CREATE_I18N_ASSETS_MODULE_START, CREATE_I18N_ASSETS_MODULE_END, GET_CONSTANTS_START, GET_CONSTANTS_END, INITIALIZE_MODULE_START, INITIALIZE_MODULE_END, ON_HOST_RESUME_START, ON_HOST_RESUME_END, 
        ON_HOST_PAUSE_START, ON_HOST_PAUSE_END, CONVERT_CONSTANTS_START, CONVERT_CONSTANTS_END, PRE_REACT_CONTEXT_END, UNPACKING_JS_BUNDLE_LOADER_CHECK_START, UNPACKING_JS_BUNDLE_LOADER_CHECK_END, UNPACKING_JS_BUNDLE_LOADER_EXTRACTED, UNPACKING_JS_BUNDLE_LOADER_BLOCKED, loadApplicationScript_startStringConvert, 
        loadApplicationScript_endStringConvert, PRE_SETUP_REACT_CONTEXT_START, PRE_SETUP_REACT_CONTEXT_END, PRE_RUN_JS_BUNDLE_START, ATTACH_MEASURED_ROOT_VIEWS_START, ATTACH_MEASURED_ROOT_VIEWS_END, CONTENT_APPEARED, RELOAD, DOWNLOAD_START, DOWNLOAD_END, 
        REACT_CONTEXT_THREAD_START, REACT_CONTEXT_THREAD_END, GET_REACT_INSTANCE_MANAGER_START, GET_REACT_INSTANCE_MANAGER_END, GET_REACT_INSTANCE_HOLDER_SPEC_START, GET_REACT_INSTANCE_HOLDER_SPEC_END, BUILD_REACT_INSTANCE_MANAGER_START, BUILD_REACT_INSTANCE_MANAGER_END, PROCESS_INFRA_PACKAGE_START, PROCESS_INFRA_PACKAGE_END, 
        PROCESS_PRODUCT_PACKAGE_START, PROCESS_PRODUCT_PACKAGE_END, CREATE_MC_MODULE_START, CREATE_MC_MODULE_END, CREATE_MC_MODULE_GET_METADATA_START, CREATE_MC_MODULE_GET_METADATA_END };
  }
}


/* Location:              C:\Users\august\Desktop\tik\df_rn_kit\classes.jar.jar!\com\facebook\react\bridge\ReactMarkerConstants.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */